openapi: 3.0.2
info:
  title: API Schema
  version: ''
  description: API for todos
paths:
  /api/todo/:
    get:
      operationId: listTodos
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
          description: ''
      tags:
      - api
    post:
      operationId: createTodo
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Todo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
          description: ''
      tags:
      - api
  /api/todo/{id}/:
    get:
      operationId: retrieveTodo
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this todo.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
          description: ''
      tags:
      - api
    put:
      operationId: updateTodo
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this todo.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Todo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateTodo
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this todo.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Todo'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyTodo
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this todo.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 150
        description:
          type: string
          maxLength: 300
        date:
          type: string
          format: date-time
          readOnly: true
        done:
          type: boolean
      required:
      - title